INSERT INTO public.categories (slug, name, icon, gradient, status, display_order) VALUES
('tractor', '{"en": "Tractor Trailers", "hi": "ट्रैक्टर ट्रेलर"}', '🚜', 'from-[#065F2E] to-[#0B7A3B]', 'active', 1),
('hydraulic', '{"en": "Hydraulic Tractor Trolley", "hi": "हाइड्रोलिक ट्रैक्टर ट्रॉली"}', '🔧', 'from-[#1a2f6f] to-[#243B8F]', 'active', 2),
('water', '{"en": "Water Tanker", "hi": "पानी का टैंकर"}', '💧', 'from-[#0c4a6e] to-[#0ea5e9]', 'active', 3),
('fabrication', '{"en": "Custom Fabrication", "hi": "कस्टम फेब्रिकेशन"}', '🔨', 'from-[#4c1d95] to-[#6d28d9]', 'active', 4),
('agri', '{"en": "Agricultural Equipment", "hi": "कृषि उपकरण"}', '🌾', 'from-[#365314] to-[#4d7c0f]', 'active', 5)
ON CONFLICT (slug) DO UPDATE SET
name = EXCLUDED.name, icon = EXCLUDED.icon, gradient = EXCLUDED.gradient;

-- Note: In a real migration you would get the category_id from the categories table and insert them, 
-- but for simplicity we will insert the products without category_id for now, 
-- or you can manually assign them in the Admin Panel.

INSERT INTO public.products (slug, title, "desc", icon, gradient, specs, featured, status, images) VALUES
('tractor-trolley', '{"en": "Tractor Trolley", "hi": "ट्रैक्टर ट्रॉली"}', '{"en": "Heavy-duty agricultural transportation trolley for farms and construction.", "hi": "खेतों और निर्माण के लिए भारी-भरकम कृषि ट्रॉली।"}', '🚜', 'from-[#065F2E] to-[#0B7A3B]', '{"nameOfPart": "Tractor Trolley", "capacity": "3–10 Ton", "size": "10 × 6 × 2 Feet (L × B × H)"}', true, 'active', '[]'),
('4w-hydraulic', '{"en": "4-Wheel Hydraulic Trolley", "hi": "चार पहिया हाइड्रोलिक ट्रॉली"}', '{"en": "Strong hydraulic lifting system for heavy commercial loads.", "hi": "भारी व्यावसायिक भार के लिए मजबूत हाइड्रोलिक लिफ्टिंग।"}', '🔧', 'from-[#1a2f6f] to-[#243B8F]', '{"nameOfPart": "4-Wheel Hydraulic Trolley", "capacity": "10–20 Ton", "size": "14 × 7 × 3 Feet (L × B × H)"}', true, 'active', '[]'),
('2w-hydraulic', '{"en": "2-Wheel Hydraulic Trolley", "hi": "दो पहिया हाइड्रोलिक ट्रॉली"}', '{"en": "Cost-effective hydraulic transport solution for farmers.", "hi": "किसानों के लिए किफायती हाइड्रोलिक परिवहन समाधान।"}', '⚙️', 'from-[#0d6471] to-[#0e9aad]', '{"nameOfPart": "2-Wheel Hydraulic Trolley", "capacity": "5–10 Ton", "size": "12 × 6 × 2.5 Feet (L × B × H)"}', true, 'active', '[]'),
('hydraulic-dumper', '{"en": "Hydraulic Dumper", "hi": "हाइड्रोलिक डम्पर"}', '{"en": "High-capacity hydraulic dumper for farming and construction.", "hi": "खेती और निर्माण के लिए उच्च क्षमता हाइड्रोलिक डम्पर।"}', '🚛', 'from-[#b45309] to-[#d97706]', '{"nameOfPart": "Hydraulic Dumper", "capacity": "10–25 Ton", "size": "16 × 7 × 4 Feet (L × B × H)"}', true, 'active', '[]'),
('water-tanker', '{"en": "Water Tanker Trailer", "hi": "वाटर टैंकर ट्रेलर"}', '{"en": "Reliable water transportation tanker for various uses.", "hi": "विभिन्न उपयोगों के लिए विश्वसनीय जल टैंकर ट्रेलर।"}', '💧', 'from-[#0c4a6e] to-[#0ea5e9]', '{"nameOfPart": "Water Tanker Trailer", "capacity": "3000–5000 Liters", "size": "10 × 5 × 5 Feet (L × B × H)"}', true, 'active', '[]'),
('medical-vehicle', '{"en": "Medical Vehicle", "hi": "मेडिकल वाहन"}', '{"en": "Customized medical and utility vehicles for healthcare.", "hi": "स्वास्थ्य सेवा के लिए कस्टमाइज़ मेडिकल वाहन।"}', '🚑', 'from-[#991b1b] to-[#dc2626]', '{"nameOfPart": "Medical Vehicle", "capacity": "As per chassis", "size": "Custom Built"}', true, 'active', '[]'),
('garbage-vehicle', '{"en": "Garbage Collection Vehicle", "hi": "कचरा संग्रह वाहन"}', '{"en": "Municipal and commercial garbage collection with durable build.", "hi": "टिकाऊ निर्माण के साथ नगर व व्यावसायिक कचरा वाहन।"}', '🗑️', 'from-[#374151] to-[#4b5563]', '{"nameOfPart": "Garbage Collection Vehicle", "capacity": "2–5 Ton / 3–6 CBM", "size": "Custom Built"}', true, 'active', '[]'),
('agri-equipment', '{"en": "Agricultural Equipment", "hi": "कृषि उपकरण"}', '{"en": "Complete range of farming equipment for modern agriculture.", "hi": "आधुनिक खेती के लिए कृषि उपकरणों की पूरी रेंज।"}', '🌾', 'from-[#365314] to-[#4d7c0f]', '{"nameOfPart": "Agricultural Implements", "capacity": "Varies", "size": "Various Sizes"}', true, 'active', '[]'),
('gates', '{"en": "Gates", "hi": "गेट"}', '{"en": "Custom fabricated steel gates for residential and commercial use.", "hi": "आवासीय और व्यावसायिक उपयोग के लिए कस्टम स्टील गेट।"}', '🚪', 'from-[#1e3a5f] to-[#374151]', '{"nameOfPart": "Steel Gate", "capacity": "N/A", "size": "Custom Dimensions"}', true, 'active', '[]'),
('railings', '{"en": "Railings", "hi": "रेलिंग"}', '{"en": "Strong and decorative railings for safety and aesthetics.", "hi": "सुरक्षा and सौंदर्य के लिए मजबूत और सजावटी रेलिंग।"}', '🛡️', 'from-[#111827] to-[#1f2937]', '{"nameOfPart": "Steel/Iron Railing", "capacity": "N/A", "size": "Custom Dimensions"}', true, 'active', '[]'),
('cultivators', '{"en": "Cultivators", "hi": "कल्टीवेटर"}', '{"en": "Durable cultivators for modern and efficient farming.", "hi": "आधुनिक और कुशल खेती के लिए टिकाऊ कल्टीवेटर।"}', '🌱', 'from-[#78350f] to-[#92400e]', '{"nameOfPart": "Cultivator", "capacity": "7-11 Tynes", "size": "Standard"}', true, 'active', '[]'),
('custom-fab', '{"en": "Custom Fabrication", "hi": "कस्टम फेब्रिकेशन"}', '{"en": "Tailor-made fabrication as per customer requirements.", "hi": "ग्राहकों की आवश्यकताओं के अनुसार कस्टम फेब्रिकेशन।"}', '🔨', 'from-[#4c1d95] to-[#6d28d9]', '{"nameOfPart": "Custom Structure", "capacity": "As Required", "size": "As Required"}', true, 'active', '[]'),
('vehicle-repair', '{"en": "Vehicle Repairing", "hi": "वाहन मरम्मत"}', '{"en": "Repair and maintenance of all agricultural and commercial vehicles.", "hi": "सभी प्रकार के कृषि और व्यावसायिक वाहनों की मरम्मत।"}', '🔩', 'from-[#7f1d1d] to-[#b91c1c]', '{"nameOfPart": "Repair Service", "capacity": "All Vehicles", "size": "N/A"}', true, 'active', '[]')
ON CONFLICT (slug) DO UPDATE SET
title = EXCLUDED.title, "desc" = EXCLUDED."desc", icon = EXCLUDED.icon, gradient = EXCLUDED.gradient, specs = EXCLUDED.specs, featured = EXCLUDED.featured, status = EXCLUDED.status, images = EXCLUDED.images;
